import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

const USER_ID = "demo-user";
async function getUser() {
  return prisma.user.upsert({
    where: { id: USER_ID },
    update: {},
    create: { id: USER_ID, name: "Demo User", email: "demo@example.com" },
  });
}

export async function GET(request: NextRequest) {
  try {
    const user = await getUser();
    const { searchParams } = new URL(request.url);

    const status = searchParams.get("status");
    const dateFrom = searchParams.get("dateFrom");
    const dateTo = searchParams.get("dateTo");
    const streamId = searchParams.get("streamId");
    const confidence = searchParams.get("confidence");

    const where: Record<string, unknown> = { userId: user.id };

    if (status) where.status = status;
    if (streamId) where.revenueStreamId = streamId;
    if (confidence) where.confidence = confidence;

    if (dateFrom || dateTo) {
      where.expectedDate = {} as Record<string, Date>;
      if (dateFrom) (where.expectedDate as Record<string, Date>).gte = new Date(dateFrom);
      if (dateTo) (where.expectedDate as Record<string, Date>).lte = new Date(dateTo);
    }

    const payouts = await prisma.pendingPayout.findMany({
      where,
      include: {
        revenueStream: { select: { name: true, type: true, color: true } },
        client: { select: { name: true } },
        linkedTransaction: {
          select: { id: true, description: true, originalAmount: true },
        },
      },
      orderBy: { expectedDate: "asc" },
    });

    return NextResponse.json(payouts);
  } catch (error) {
    console.error("GET /api/pending-payouts error:", error);
    return NextResponse.json(
      { error: "Failed to fetch pending payouts" },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const user = await getUser();
    const body = await request.json();

    const {
      revenueStreamId,
      clientId,
      amount,
      currency,
      convertedAmount,
      expectedDate,
      periodCovered,
      status,
      confidence,
      sourceDetail,
      notes,
      isAutoGenerated,
    } = body;

    if (!revenueStreamId || amount === undefined || !expectedDate) {
      return NextResponse.json(
        { error: "revenueStreamId, amount, and expectedDate are required" },
        { status: 400 }
      );
    }

    const payout = await prisma.pendingPayout.create({
      data: {
        userId: user.id,
        revenueStreamId,
        clientId: clientId || null,
        amount,
        currency: currency || user.primaryCurrency,
        convertedAmount: convertedAmount ?? null,
        expectedDate: new Date(expectedDate),
        periodCovered: periodCovered || null,
        status: status || "expected",
        confidence: confidence || "medium",
        sourceDetail: sourceDetail || null,
        notes: notes || null,
        isAutoGenerated: isAutoGenerated || false,
      },
      include: {
        revenueStream: { select: { name: true, type: true } },
        client: { select: { name: true } },
      },
    });

    return NextResponse.json(payout, { status: 201 });
  } catch (error) {
    console.error("POST /api/pending-payouts error:", error);
    return NextResponse.json(
      { error: "Failed to create pending payout" },
      { status: 500 }
    );
  }
}
